name: Deploy dev to AWS

#turn off deploy to AWS 
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      API_URL: ${{secrets.API_URL}}
      CLIENT_URL: ${{secrets.CLIENT_URL}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          touch .env
          echo CLIENT_ID="$CLIENT_ID" >> .env
          echo API_URL="$API_URL" >> .env
          echo CLIENT_URL=project3.eaglesoftwareteam.com >> .env
          echo SITE_URL=project3.eaglesoftwareteam.com >> .env

      - run: npm install
      - run: npm run build
      - run: npm run bundle

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "project3.eaglesoftwareteam.com"
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/seiv2025/p3/t9"

